
services:
 

 
  maisonhote:
    container_name: maisonhote
    build: D:\esprit\5SAE\Microservices\AgenceVoyageMicro-MaisonHotes\AgenceVoyageMicroMaisonHotes
    ports:
      - "8082:8082"
    hostname: maisonhote
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_2:3306/agencevoyage?autoReconnect=true&useSSL=false
      
    image: "maisonhote"
    depends_on:
      - mysql_2

  apigateway:
      container_name: apigateway
      build: D:\esprit\5SAE\Microservices\AgenceVoyageMicro-ApiGetWay\AgenceVoyageMicro-ApiGetWay
      ports:
        - "8089:8089"
      hostname: apigateway
      environment:
        - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
      image: "apigateway"
      depends_on:
        - discovery

  mysql_2:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=agencevoyage
    ports:
      - 3306:3306

      
  discovery:
    build: D:\esprit\5SAE\Microservices\AgenceVoyageMicro-ServerEureka\AgenceVoyageMicro-ServerEureka
    ports:
      - "8761:8761"
    image: "discovery-service"    
