services:
  mysql_2:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=offre
    ports:
      - "3308:3306"
    restart: always

  discovery:
    build: C:\Users\mayah\OneDrive\Desktop\micro Project\AgenceVoyageMicro-ServerEureka\AgenceVoyageMicro-ServerEureka
    image: "discovery-service"
    ports:
      - "8761:8761"
    depends_on:
      - mysql_2
networks:
  my_network:
    driver: bridge