version: "2.7.4"
services:

  maisonhote:
    container_name: maisonhotetest
    build: D:\esprit\5SAE\Microservices\AgenceVoyageMicro-MaisonHotes\AgenceVoyageMicroMaisonHotes
    ports:
      - "8081:8081"
    hostname: maisonhotetest
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_2:3306/agencevoyage?autoReconnect=true&useSSL=false

    image: "maisonhotetest"
    depends_on:
      - mysql_2




  apigateway:
    container_name: apigateway
    build: D:\esprit\5SAE\Microservices\AgenceVoyageMicro-ApiGetWay\AgenceVoyageMicro-ApiGetWay
    ports:
      - "8089:8089"
    hostname: apigateway
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
    image: "apigateway"
    depends_on:
      - discovery


  mysql_2:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=agencevoyage
    ports:
      - 3308:3306


  userservicemongo:
    build: D:\esprit\5SAE\Microservices\AgenceVoyageMicro-mongodb\AgenceVoyageMicro-mongodb
    ports:
      - "5000:5000"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka
    command: npm start

    image: userservicemongo
    depends_on:
      - discovery

  discovery:
    build: D:\esprit\5SAE\Microservices\AgenceVoyageMicro-ServerEureka\AgenceVoyageMicro-ServerEureka
    ports:
      - "8761:8761"
    image: "discovery-service"

  angular-service:
    # The name of the service
    container_name: angularcontainer # Container name
    build: D:\esprit\5SAE\Microservices\AgenceVoyageMicro-Client\AgenceVoyageMicro-Client\ # Location of our Dockerfile
    volumes:
      # Volume binding
      - './angular:/src/app'
    ports:
      - '4200:4200' # Port mapping
